<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Citizen extends Model
{
    use HasFactory;

   protected $fillable = [
        'identity_type',
        'identity_number',
        'first_name',
        'second_name',
        'third_name',
        'family_name',
        'gender',
        'birth_of_date',
        'marital_status',
        'spouse_id_number',
        'spouse_id_type',
        'spouse_first_name',
        'spouse_second_name',
        'spouse_third_name',
        'spouse_family_name',
        'is_war_victim',
        'is_disabled',
        'disability_type',
        'has_chronic_diseases',
        'displaced_or_resident',
        'mobile_number1',
        'mobile_number2',
        'original_governorate',
        'current_governorate',
        'population_cluster',
        'neighborhood',
        'street',
        'nearest_landmark',
        'city',
        'address',
        'family_members_count',
        'number_of_male',
        'number_of_female',
        'children_Under_5',
        'children_Under_2',
        'children_Under_3',
        'children_6_18',
        'children_5_16',
        'number_of_school_students',
        'number_of_university_students',
        'number_of_infants',
        'number_of_people_with_disabilities',
        'number_of_people_with_chronic_diseases',
        'number_of_elderly_people_over_60',
        'number_of_pregnant_women',
        'number_of_breastfeeding_women',
        'number_of_injured_due_to_war',
        'care_for_non_family_members',
        'number_of_children_cared_for_not_in_family_under_18',
        'reason_of_care',
        'lost_family_member_during_war',
        //Needs
        'urgent_basic_needs_for_family',
        'secondary_needs_for_family',
        'sources_of_family_income',
        'monthly_income_shekels',
        'unable_to_use_land_or_properties_due_to_war',
        'housing_ownership',
        'type_of_housing',
        'extent_of_housing_damage_due_to_war',
        'displaced_due_to_war_and_changed_housing_location',
        'displaced_governorate',
        'displaced_population_cluster',
        'displaced_street',
        'displaced_address',
        'displaced_place_of_displacement',
        'housing_type',
        'account_holder_name',
        'bank_name_branch',
        'account_holder_id_number',
        'account_number',
        'has_war_damage',
        'damage_type',
        'agree_to_share_data_for_assistance',
    ];
}
